### ISSUE TITLE
SSO: Complete Google Workspace form

### ISSUE THREAD

**Issue by stsewd** [readthedocs/ext-theme#219]
It's always marked as disabled, and doesn't show the domain that will be used.

![Screenshot 2023-09-27 at 11-34-20 santosorg - Authorization - Read the Docs](https://github.com/readthedocs/ext-theme/assets/4975310/5eeec74d-0b5c-40c6-83ec-3306775e06e1)

And after https://github.com/readthedocs/readthedocs-corporate/pull/1595 there is no need for the user to set the domain, but the domain from their Google account is used automatically instead.

Which means that users will need to connect their own account to Google (linked to a domain) before setting up the integration, that's why I put this note in case they don't have it set up.

https://github.com/readthedocs/readthedocs-corporate/blob/9e31a22ff99cbe7c26c5d2002ad619ad1f20ee36/readthedocsinc/corporate/templates/organizations/admin/sso_edit.html#L52-L62

**Comment by agjohnson** [comment]
I add #277 to rework this view a bit more and rely on the underlying form instance instead of doing a custom form. I found it too hard to line things up.

I did not do anything special with the domain field (which above sounds like more of a read only field?) and did not do anything yet to ensure the user has a provider linked (this should probably be a validation error on the form).

- UI changes are in #277 
- Form changes are in readthedocs/readthedocs-corporate#1730
