### ISSUE TITLE
Addons: split settings page per-addon

### ISSUE THREAD

**Issue by humitos** [readthedocs/ext-theme#293]
In the short term, as we keep adding configuration options for each addon, we will need to split the addons settings' page per-addon somehow. I'm creating this issue here to keep track of this and have this discussion together.

There are some different proposals here:

* Use the same settings page for all the addons and add a header for each of them (idea partially implemented in https://github.com/readthedocs/readthedocs.org/pull/11031)
* Split the settings page into different pages per-addon (**different** URL, forms, etc)
* Split the settings page into different **tags** per-addon (same URL, form, etc)

Reference: https://github.com/readthedocs/readthedocs.org/pull/11069#pullrequestreview-1846423142

**Comment by agjohnson** [comment]
Since this was opened, do we have any more opinions on what exactly we want here? Looking at the current form, it's not too overwhelming at the moment so I'm not immediately drawn to splitting this up into multiple forms/views/tabs. At very least, having 6 form instances feels overkill.

Maybe it helps to start from what other fields do we see us needing here?

I feel like I might want a little bit more onboarding content for some of the settings, but this could also be covered with documentation.

**Comment by agjohnson** [comment]
I think I found a fairly minimal solution for now, and I avoided splitting up the form and views into multiple instances. My change provides more space for fields and supporting content for each addon, like onboard placeholder segments or images/etc, but leaves the form instance untouched.

I'd still like to know if this fits in our plans for fields and usage of this form, but at very least it feels adaptable without being too much maintenance.
