### ISSUE TITLE
Add resync repository button in the version creation view template

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/ext-theme#65]
The resync repository button should be in the version list template so that it's obvious how to get newly added versions to show up. Right now, you have to know to trigger a build, and that is bad UX.

**Comment by agjohnson** [comment]
@humitos you probably have the most context here, this is another relatively simple change, and some missing UX at the moment. I would add this on the version add view, not the listing view.

**Comment by humitos** [comment]
Here, we would need:

1. an UI element that trigger a Celery task on the backend
2. the Celery task is this one https://github.com/readthedocs/readthedocs.org/blob/98ec4abf92d864b6e29cbb9cce9f036fc5f6c996/readthedocs/projects/tasks/builds.py#L244-L264
3. poll the "task's faked response" (as we do for re-sync remote repositories) and refresh the page with the new versions

I think this is pretty low priority tho, since the needing to re-sync the versions it's an edge case that only happens on not well-configured repositories.

**Comment by agjohnson** [comment]
What number/percent of projects are not well-configured?

**Comment by humitos** [comment]
> What number/percent of projects are not well-configured?

That's a hard question to answer without executing a big query in the database; but you can do it if you want from the replica or similar. This query would be:

- projects without _any integration_ configured
- projects that are not spam (this check is expensive since it's done 1 by 1)

Personally, I think this issue is not a priority at the moment, mainly because we don't have users complaining about this and there is a workaround (trigger a build for `latest`) in case they hit this issue. At this point, it's a "nice to have" in my opinion considering the amount of work required.

**Comment by agjohnson** [comment]
Seems pretty easy to get, though I don't quite understand the state that triggers this UX either. To ballpark though:

```python
proj_misconfigured = Project.objects.filter(integrations__isnull=True, organizations__disabled=False).exclude(name="demo").count()
proj_total = Project.objects.filter(organizations__disabled=False).count()
```

```python
proj_misconfigured = Project.objects.filter(integrations__isnull=True, spam_rules__isnull=True).exclude(name="demo").count()
proj_total = Project.objects.filter(spam_rules__isnull=True).count()
```

Commercial: 3% of active organization projects are not set up correctly
Community: 0.4% are not set up correctly

Given I'm almost certainly not getting an accurate view here, I think it's probably worth _something_ here, but would also agree we don't need a special feature like a sync button.

Instead, I'd say a conditional "This project is missing an integration, add one or <a>rebuild your project</a> to sync versions" sort of notification is super easy, and clear enough to do the job. The troubleshooting step and fix here, building the project, is not clear at all right now.

Going back to the discuss on integration warnings (#28), if we end up adding model state like `Project.objects.filter(integrations__is_invalid=False).exists()` that's something we'd be able to reuse here.

- #28

**Comment by humitos** [comment]
> Instead, I'd say a conditional "This project is missing an integration, add one or rebuild your project to sync versions" sort of notification is super easy, and clear enough to do the job. The troubleshooting step and fix here, building the project, is not clear at all right now.

This is probably a good solution for now, yes 👍🏼 

> Going back to the discuss on integration warnings (#28), if we end up adding model state like `Project.objects.filter(integrations__is_invalid=False).exists()` that's something we'd be able to reuse here.

We have a `project.has_valid_webhook` (https://github.com/readthedocs/readthedocs.org/blob/4770af1de0bba949c79a0bb42bfbc08a95e7cda5/readthedocs/projects/models.py#L520-L523) that we may can use here as well. However, I'm not sure how accurate it is, since I'm not sure we are updating if the integration becomes invalid or similar. I think once we mark it as `True` we never changed it back to `False`.

**Comment by humitos** [comment]
> Commercial: 3% of active organization projects are not set up correctly
> Community: 0.4% are not set up correctly

Not sure how this ended up in my current sprint, but I don't think it's a huge priority to be on my list taking into account the other tasks I have to work on. I'm unassigned it from me and leave on the sprint in case someone else can take it.

**Comment by agjohnson** [comment]
Noted in chat, but this is me distributing easy issues to start with.

**Comment by agjohnson** [comment]
No one has picked this up. I am dropping it from our sprints.
